/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Membreño
 */
public class MS_Frm_Recuperacion_Contraseña_Reconocer_Usuaraio extends javax.swing.JFrame {
    
    private JFrame Recuperacion = new JFrame();

    /**
     * Creates new form MS_Frm_Recuperacion_Contraseña
     */
    public MS_Frm_Recuperacion_Contraseña_Reconocer_Usuaraio() {
        initComponents();
        
        Recuperacion.setContentPane(PanelPrincipal);
        
        Recuperacion.pack();
        
        Recuperacion.setVisible(true);
        
        Recuperacion.setLocationRelativeTo(null);
        
        Recuperacion.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                 
        Recuperacion.setTitle("Recuperacion de contraseña");
    }
    public static String Id_Usuario= "";
    public static int Secuencia_Usuario=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txt_Usuario_Recuperacion = new javax.swing.JTextField();
        Boton_Siguiente = new javax.swing.JButton();
        Boton_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Bienvenido al asistente de recuperacion de contraseña");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Ingresa tu ID de Usuario");

        Txt_Usuario_Recuperacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Boton_Siguiente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Boton_Siguiente.setText("Siguiente");
        Boton_Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SiguienteActionPerformed(evt);
            }
        });

        Boton_Salir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Boton_Salir.setText("Salir");
        Boton_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(Txt_Usuario_Recuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Boton_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(95, 95, 95)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_Usuario_Recuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Siguiente)
                    .addComponent(Boton_Salir))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SalirActionPerformed
        Recuperacion.dispose();
        new Ms_Frm_Login();
    }//GEN-LAST:event_Boton_SalirActionPerformed

    private void Boton_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SiguienteActionPerformed
           
        int vercasilla = vericarcasilla();
        if(vercasilla!=1){
            JOptionPane.showMessageDialog(null, "Usuario no valido");
            new Ms_Frm_Login();
            Recuperacion.dispose();
        }else{
                boolean var = verificarUsuario();
                if (var==true){
                traerSecuencia();
                new Ms_Frm_Recuperacion_contraseña_preguntas();
                Recuperacion.dispose();
                }else{
                    new Ms_Frm_Login();
                    Recuperacion.dispose();
                }
        }
        
        
        
    }//GEN-LAST:event_Boton_SiguienteActionPerformed

    public JTextField getTxt_Usuario_Recuperacion() {
        return Txt_Usuario_Recuperacion;
    }

    public int vericarcasilla(){
    
        int ver = 0;
        if (Txt_Usuario_Recuperacion.getText().isEmpty()){
        
        }else{
               ver = 1;
        }
        return ver;
    
    }
    
    public boolean verificarUsuario(){
    
            boolean var = true;
            ResultSet Usuario = null;           
            Usuario = Ms_Conexion.Consulta("SELECT[Id_Usuario]FROM [SRV_BD_APP_SINVEN].[dbo].[TBL_MS_REGISTRO_USUARIO]WHERE[Id_Usuario]="+"'"+Txt_Usuario_Recuperacion.getText()+"'");       
           
        
            try {
                if(Usuario.next())  {
                    Id_Usuario=Usuario.getString(1);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "El usuario no existe");
                    
                    var = false;
                }
                 
            } catch (SQLException ex) {
            Logger.getLogger(Ms_Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
             }
            
            return var;
    }
    
    
    public int traerSecuencia(){
            int secuencia_Usuario = 0;
            ResultSet secuencia= null;
            secuencia = Ms_Conexion.Consulta("SELECT[Secuencia_Usuario]FROM [SRV_BD_APP_SINVEN].[dbo].[TBL_MS_REGISTRO_USUARIO]WHERE[Id_Usuario]="+"'"+Id_Usuario+"'");
            
            try {
                if(secuencia.next()){
                Secuencia_Usuario = secuencia.getInt(1);
                    System.out.println(Secuencia_Usuario);
                secuencia_Usuario=1;
                }
            } catch (Exception e) {
            }
            
            return secuencia_Usuario;
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir;
    private javax.swing.JButton Boton_Siguiente;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextField Txt_Usuario_Recuperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
